### ISSUE TITLE
如果有时间日志的print能不能换成loguru或者logging,方便后期控制打印级别

### ISSUE THREAD

**Issue by Warlock1994** [Cassius0924/WeChatter#25]

**Comment by Warlock1994** [comment]
还有requirements.txt是不是少了python-multipart我用docker新建环境少了这个

**Comment by Cassius0924** [comment]
有计划使用logging，正在逐步重构代码。第一次开发Python，没有经验。

如果有兴趣，欢迎提交PR。

**Comment by Cassius0924** [comment]
> 还有requirements.txt是不是少了python-multipart我用docker新建环境少了这个

已添加 #26

**Comment by Cassius0924** [comment]
貌似 Loguru 更友好，使用 Loguru 👍
