### ISSUE TITLE
会封号吗

### ISSUE THREAD

**Issue by crazybee881113** [Cassius0924/WeChatter#54]
大佬，微信会封号吗

**Comment by Cassius0924** [comment]
目前我使用了两个月，一切正常。具体可以去上游项目 [wechatbot-webhook](https://github.com/danni-cool/wechatbot-webhook) 的 issue 里看看。
本质是在将你微信登录到 Linux 的桌面微信中，所以理论上没有问题，但依然推荐用小号。

**Comment by Cassius0924** [comment]
相关 issue：
danni-cool/wechatbot-webhook#25
danni-cool/wechatbot-webhook#12
