### ISSUE TITLE
消息未回复提醒 check_unanswered_messages

### ISSUE THREAD

**Issue by z1298808165** [Cassius0924/WeChatter#91]
大佬您好，不知道能否实现对未回复消息的提醒，情景是如果检测到机器人账号在指定时间（例如十分钟）未回复消息，则自动转发消息给到指定用户。

**Comment by Cassius0924** [comment]
可以实现，可以给消息转发加一个
`unanswered_timeout`配置项。

对于个人消息转发，`unanswered_timeout`作用于机器人本身。

但是对于群消息转发，`unanswered_timeout`应该作用于全体群员还是作用于机器人本身。换句话说，应该应该如何判断某条裙消息是否已回复？

**Comment by z1298808165** [comment]
> 可以实现，可以给消息转发加一个 `unanswered_timeout`配置项。
> 
> 对于个人消息转发，`unanswered_timeout`作用于机器人本身。
> 
> 但是对于群消息转发，`unanswered_timeout`应该作用于全体群员还是作用于机器人本身。换句话说，应该如何判断某条群消息是否已回复？

`unanswered_timeout`只作用于机器人本身，当然，对于群消息内容如果可以判断“消息发送人”，那么则可以设定`from_list`。

对于判断某条群消息是否已回复，消息在接收时记录消息ID，然后将触发机器人的消息排成队列，队列中包含消息ID以及相关时间（可以是消息发送时间，也可以是从0计时，也可以是超时倒计时之类的时间记录），当队列消息满足`unanswered_timeout`条件时则自动转发消息，同时移出队列。

以上仅为个人想法，不知是否可以实现。

**Comment by z1298808165** [comment]
> 可以实现，可以给消息转发加一个 `unanswered_timeout`配置项。
> 
> 对于个人消息转发，`unanswered_timeout`作用于机器人本身。
> 
> 但是对于群消息转发，`unanswered_timeout`应该作用于全体群员还是作用于机器人本身。换句话说，应该如何判断某条群消息是否已回复？

建议`unanswered_timeout`仅作用于机器人本身。

当然对于某条群消息是否已回复，这个判断比较苛刻，需要满足条件：1.该消息@了机器人或`from_list`里的用户 2.回复的消息引用了原消息 3.后台可以识别出是引用哪条消息 4.判断回复消息的用户是否是指定用户（即条件1的触发账号）。

对于机器人本身而言，无论是私聊还是群聊，可能也会出现在电脑端或者手机端进行人工回复消息的情况，如果在其它设备上进行了回复，这也需要判断为已经回复。
