### ISSUE TITLE
私聊无法畅通聊天

### ISSUE THREAD

**Issue by javak8** [Cassius0924/WeChatter#93]
私聊情况下，每次必须带命令 否则报”该消息不是命令类型“

群聊的情况下报”送消息失败，接收者为空：_send_msg1“

**Comment by Cassius0924** [comment]
> 每次必须带命令 否则报”该消息不是命令类型“

这是终端报的吧，`该消息不是命令类型`此消息为`DEBUG`级别的调试输出，你可以使用下面命令屏蔽DEBUG输出：
```
export WECHATTER_LOG_LEVEL=INFO
```

**Comment by Cassius0924** [comment]
> 群聊的情况下报”送消息失败，接收者为空：_send_msg1“

不太清楚情况，提供一下截图

**Comment by javak8** [comment]
我有两个疑问
1. 私聊情况下必须每次都要到指令吗？我测下来好像不带指令就不会回复。
没有带命令的场景，现象不回复如下图
![1710902686207](https://github.com/Cassius0924/WeChatter/assets/162659858/fe731319-7858-4b65-8531-6c2034dfabcb)
后台日志
![1710902850814](https://github.com/Cassius0924/WeChatter/assets/162659858/97b1da96-40db-4cfe-93a4-47b545423c53)

带命令的场景，可以复如下图（但是私聊下每次代替是很麻烦）
![1710902918478](https://github.com/Cassius0924/WeChatter/assets/162659858/e357d761-bcd3-49cd-8d59-082a0bdceaa0)
后台日志
![59a2f996a2023b8153ae59d90bf9e3d](https://github.com/Cassius0924/WeChatter/assets/162659858/107c8d71-d968-404e-89ed-90348e9dd9c8)

2. 群聊种报错说找不到接收人如下图，不知道我哪里配置不对还是
![a84f1901e7a90a67e9f1d58a2342a61](https://github.com/Cassius0924/WeChatter/assets/162659858/7135f8e2-536a-4758-bb79-8a2c77df5762)
后台日志
![093f766d67e4f340893f266e3c1ef6e](https://github.com/Cassius0924/WeChatter/assets/162659858/95d77e05-fdb4-44f0-a093-c44e41417878)

部署方式，后台Docker部署，命令如下：
docker run -d \
--name wxBotWebhook \
-p 2000:3001 \
-e LOGIN_API_TOKEN="wechatter" \
-e RECVD_MSG_API="http://10.75.190.8:2030/receive_msg" \
dannicool/docker-wechatbot-webhook


docker run -d \
--name WeChatter \
-p 2030:4000 \
-v ./config.yaml:/wechatter/config.yaml \
-e WECHATTER_LOG_LEVEL=DEBUG \
cassius0924/wechatter


配置
![1710903411075](https://github.com/Cassius0924/WeChatter/assets/162659858/e28f04f2-b1e1-4ded-b9c3-05e703590f6c)


请大佬指导，谢谢啦

**Comment by Cassius0924** [comment]
> 必须每次都要到指令吗？

目前的设计是这样的，对于GPT命令的持续聊天来说，确实不是很方便。

但我目前还没想到更好的方式，带上命令是为了区分普通聊天消息和命令消息，如果不带上命令直接则可能出现正常的聊天对话被误判为命令的情况。

目前可以使用自定义命令关键词的配置来缓解这一情况。
```yaml
custom_command_key_dict:
  gpt: [ "!"，"！" ]
```
这样就可以将`!`（半角）和`！`（全角）都映射成`gpt`，你就可以使用“! 你好”（注意空格区分）来触发GPT命令。

**Comment by Cassius0924** [comment]
> 群聊种报错说找不到接收人如下图，不知道我哪里配置不对还是

日志中的群名称为空，所以导致消息发送失败。

这是底层微信的web协议不稳定问题导致的，暂时无法解决，只能通过重新登陆机器人来解决。

![image](https://github.com/Cassius0924/WeChatter/assets/62874592/dad15bf6-f512-4a70-b46c-439b30d51a6f)

**Comment by javak8** [comment]
谢谢，明白了，第二个问题好了
对于私聊能否默认状态下是GPT, 然后再判断是否命令开头 这样的方式问答。这样体验可能会好一些。
谢谢啦

**Comment by Cassius0924** [comment]
可以实现将指定用户设定成默认触发GPT命令的模式。

这样可以实现不带`GPT`关键词触发GPT命令。

这种情况下，带命令关键词的消息会正常触发相对应的命令，其余消息均判断为GPT命令。

但是这样做会导致所指定的用户难以进行正常聊天。
