### ISSUE TITLE
机器人提示发送消息失败，接受者为空

### ISSUE THREAD

**Issue by Linqingtong** [Cassius0924/WeChatter#96]

**Comment by Linqingtong** [comment]
wechatter.sender.sender:validate_wrapper:120 - 发送消息失败，接收者为空：_send_msg1
wechatter     | INFO:     172.18.0.1:44688 - "POST /message

**Comment by Linqingtong** [comment]
消息内容：你好
消息来源：id='' name='' admin_id_list=[] member_list=[] is_gaming=False

**Comment by pgqicl** [comment]
me too

**Comment by pgqicl** [comment]
消息来源：id='' name='' admin_id_list=[] member_list=[] is_gaming=False

**Comment by vv5126** [comment]
_send_msg1
is_group默认改为False能解

**Comment by pineappleir** [comment]
我也是这个问题呢：
2024-08-29 07:10:42 | ERROR | wechatter.sender.sender:validate_wrapper:120 - 发送消息失败，接收者为空：_send_msg1

**Comment by pineappleir** [comment]
> > 我也是这个问题呢： 2024-08-29 07:10:42 | ERROR | wechatter.sender.sender:validate_wrapper:120 - 发送消息失败，接收者为空：_send_msg1
> 
> 什么情况下会报错这个？

任何情况都会报，甚至我修改了管理员之后直接加载不出来了

**Comment by Cassius0924** [comment]
> > > 我也是这个问题呢： 2024-08-29 07:10:42 | ERROR | wechatter.sender.sender:validate_wrapper:120 - 发送消息失败，接收者为空：_send_msg1
> > 
> > 
> > 什么情况下会报错这个？
> 
> 任何情况都会报，甚至我修改了管理员之后直接加载不出来了

多半是底层wechaty问题，尝试在手机退出电脑登录，重新扫码登录机器人

**Comment by pineappleir** [comment]
> > > > 我也是这个问题呢： 2024-08-29 07:10:42 | ERROR | wechatter.sender.sender:validate_wrapper:120 - 发送消息失败，接收者为空：_send_msg1
> > > 
> > > 
> > > 什么情况下会报错这个？
> > 
> > 
> > 任何情况都会报，甚至我修改了管理员之后直接加载不出来了
> 
> 多半是底层wechaty问题，尝试在手机退出电脑登录，重新扫码登录机器人

试过了，也不行而且二维码每次都显示错位，需要去二次处理一遍

**Comment by pineappleir** [comment]
wxbotwebhook  | [2024-08-29T08:38:20.540] [INFO] - 🌱 User Contact<y> logged in
wxbotwebhook  | [2024-08-29T08:38:20.540] [INFO] - 💬 你的推消息 api 为：http://localhost:3001/webhook/msg/v2?token=wechatter
wxbotwebhook  | [2024-08-29T08:38:20.540] [INFO] - 📖 发送消息结构 API 请参考: https://github.com/danni-cool/wechatbot-webhook?tab=readme-ov-file#%EF%B8%8F-api
wxbotwebhook  |
wxbotwebhook  | [2024-08-29T08:38:20.544] [INFO] - starting fetching api: http://wechatter:4000/receive_msg
wechatter     | 2024-08-29 08:38:20 | INFO | wechatter.app.routers.wechat:recv_wechat_msg:50 - 收到系统事件：system_event_login
wechatter     | 2024-08-29 08:38:20 | INFO | wechatter.sender.notifier:notify_logged_in:28 - 微信机器人启动成功
wechatter     | 2024-08-29 08:38:20 | INFO | wechatter.sender.sender:mass_send_msg_to_admins:395 - 发送消息给管理员：['文件传输助手', 'z']
wxbotwebhook  | [2024-08-29T08:38:22.697] [INFO] - 调用 bot api 发送 消息 给 Contact<文件传输助手>: 微信机器人启动成功
wxbotwebhook  | [2024-08-29T08:38:22.698] [INFO] - starting fetching api: http://wechatter:4000/receive_msg
wxbotwebhook  | [2024-08-29T08:38:23.715] [INFO] - 调用 bot api 发送 消息 给 Contact<z>: 微信机器人启动成功
wxbotwebhook  | [2024-08-29T08:38:23.716] [INFO] - starting fetching api: http://wechatter:4000/receive_msg
wechatter     | 2024-08-29 08:38:23 | INFO | wechatter.sender.sender:logging_wrapper:80 - 发送消息成功，发送给：文件传输助手，发送的内容：{'type': 'text', 'content': '微信机器人启动成功'}
wechatter     | 2024-08-29 08:38:23 | INFO | wechatter.sender.sender:logging_wrapper:80 - 发送消息成功，发送给：z，发送的内容：{'type': 'text', 'content': '微信机器人启动成功'}
wechatter     | 2024-08-29 08:38:23 | INFO | wechatter.sender.sender:mass_send_msg_to_admins:400 - 发送消息给管理员群组：['机器人测试']
wechatter     | 2024-08-29 08:38:23 | ERROR | wechatter.sender.sender:logging_wrapper:59 - 发送消息失败，所有消息均发送失败: [{'to': '机器人测试', 'isRoom': True, 'data': {'type': 'text', 'content': '微信机器人启动成功'}}]
wechatter     | INFO:     172.18.0.2:56700 - "POST /receive_msg HTTP/1.1" 200 OK
wechatter     | 消息内容：微信机器人启动成功
wechatter     | 消息来源：id='' name='' admin_id_list=[] member_list=[] is_gaming=False
wechatter     | 是否@：False
wechatter     | 是否引用：False
wechatter     | INFO:     172.18.0.2:56706 - "POST /receive_msg HTTP/1.1" 200 OK
wechatter     | 消息内容：微信机器人启动成功
wechatter     | 消息来源：id='' name='' admin_id_list=[] member_list=[] is_gaming=False
wechatter     | 是否@：False
wechatter     | 是否引用：False
wechatter     | INFO:     172.18.0.2:56722 - "POST /receive_msg HTTP/1.1" 200 OK
wxbotwebhook  | [2024-08-29T08:38:24.872] [INFO] - Message: Message#Unknown[🗣Contact<y>]
wxbotwebhook  | [2024-08-29T08:38:24.873] [INFO] - Message: Message#Unknown[🗣Contact<y>]
wxbotwebhook  | [2024-08-29T08:38:24.874] [INFO] - Message: Message#Unknown[🗣Contact<y>]
wxbotwebhook  | [2024-08-29T08:38:24.874] [INFO] - starting fetching api: http://wechatter:4000/receive_msg
wxbotwebhook  | [2024-08-29T08:38:24.877] [INFO] - starting fetching api: http://wechatter:4000/receive_msg
wxbotwebhook  | [2024-08-29T08:38:24.879] [INFO] - starting fetching api: http://wechatter:4000/receive_msg
wechatter     | INFO:     172.18.0.2:56726 - "POST /receive_msg HTTP/1.1" 422 Unprocessable Entity
wxbotwebhook  | [2024-08-29T08:38:24.910] [ERROR] - HTTP error When trying to send Data to RecvdApi: 422
wechatter     | INFO:     172.18.0.2:56736 - "POST /receive_msg HTTP/1.1" 422 Unprocessable Entity
wxbotwebhook  | [2024-08-29T08:38:24.912] [ERROR] - HTTP error When trying to send Data to RecvdApi: 422
wechatter     | INFO:     172.18.0.2:56742 - "POST /receive_msg HTTP/1.1" 422 Unprocessable Entity
wxbotwebhook  | [2024-08-29T08:38:24.919] [ERROR] - HTTP error When trying to send Data to RecvdApi: 422
wxbotwebhook  | [2024-08-29T08:38:25.632] [ERROR] -
wxbotwebhook  | Error: Client network socket disconnected before secure TLS connection was established
wxbotwebhook  |
wxbotwebhook  | [2024-08-29T08:38:25.632] [INFO] - starting fetching api: http://wechatter:4000/receive_msg
wechatter     | 2024-08-29 08:38:25 | INFO | wechatter.app.routers.wechat:recv_wechat_msg:50 - 收到系统事件：system_event_error
wechatter     | INFO:     172.18.0.2:56744 - "POST /receive_msg HTTP/1.1" 200 OK
wxbotwebhook  | [2024-08-29T08:38:28.157] [INFO] - Message: Message#Unknown[🗣Contact<y>]
wxbotwebhook  | [2024-08-29T08:38:28.158] [INFO] - Message: Message#Unknown[🗣Contact<y>]
wxbotwebhook  | [2024-08-29T08:38:28.158] [INFO] - starting fetching api: http://wechatter:4000/receive_msg
wxbotwebhook  | [2024-08-29T08:38:28.162] [INFO] - starting fetching api: http://wechatter:4000/receive_msg
wechatter     | INFO:     172.18.0.2:46308 - "POST /receive_msg HTTP/1.1" 422 Unprocessable Entity
wxbotwebhook  | [2024-08-29T08:38:28.171] [ERROR] - HTTP error When trying to send Data to RecvdApi: 422
wechatter     | INFO:     172.18.0.2:46312 - "POST /receive_msg HTTP/1.1" 422 Unprocessable Entity
wxbotwebhook  | [2024-08-29T08:38:28.175] [ERROR] - HTTP error When trying to send Data to RecvdApi: 422
wxbotwebhook  | [2024-08-29T08:38:36.625] [INFO] - Message: Message#Unknown[🗣Contact<y>]
wxbotwebhook  | [2024-08-29T08:38:36.625] [INFO] - starting fetching api: http://wechatter:4000/receive_msg
wechatter     | INFO:     172.18.0.2:46316 - "POST /receive_msg HTTP/1.1" 422 Unprocessable Entity
wxbotwebhook  | [2024-08-29T08:38:36.633] [ERROR] - HTTP error When trying to send Data to RecvdApi: 422
wxbotwebhook  | [2024-08-29T08:38:47.580] [INFO] - Message: Message#Unknown[🗣Contact<y>]
wxbotwebhook  | [2024-08-29T08:38:47.580] [INFO] - Message: Message#Text[🗣Contact<y>]  /help
wxbotwebhook  | [2024-08-29T08:38:47.581] [INFO] - starting fetching api: http://wechatter:4000/receive_msg
wxbotwebhook  | [2024-08-29T08:38:47.583] [INFO] - starting fetching api: http://wechatter:4000/receive_msg
wxbotwebhook  | [2024-08-29T08:38:47.609] [INFO] - Message: Message#Image[🗣Contact<@4a2b415bb99cbf66452ac0f02dc111a 5b776594062ca766fcc1bda96bb95e044>@👥Room<x>]
wechatter     | INFO:     172.18.0.2:49704 - "POST /receive_msg HTTP/1.1" 422 Unprocessable Entity
wxbotwebhook  | [2024-08-29T08:38:47.636] [ERROR] - HTTP error When trying to send Data to RecvdApi: 422
wechatter     | 消息内容：/help
wechatter     | 消息来源：id='' name='' admin_id_list=[] member_list=[] is_gaming=False
wechatter     | 是否@：False
wechatter     | 是否引用：False
wechatter     | 2024-08-29 08:38:47 | INFO | wechatter.message.message_handler:handle_message:127 - 获取帮助信息。
wechatter     | 2024-08-29 08:38:47 | ERROR | wechatter.sender.sender:validate_wrapper:120 - 发送消息失败，接收者为空：_send_msg1
wechatter     | INFO:     172.18.0.2:49708 - "POST /receive_msg HTTP/1.1" 200 OK

**Comment by pineappleir** [comment]
![image](https://github.com/user-attachments/assets/6cf9e36d-bd9f-4e82-829d-18b67beb7567)
二维码出来是长这样，扫不了，我每次都得丢给gpt处理一遍

**Comment by Cassius0924** [comment]
> ![image](https://private-user-images.githubusercontent.com/89891103/362601860-6cf9e36d-bd9f-4e82-829d-18b67beb7567.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjIzMDYsIm5iZiI6MTcyNDkyMjAwNiwicGF0aCI6Ii84OTg5MTEwMy8zNjI2MDE4NjAtNmNmOWUzNmQtYmQ5Zi00ZTgyLTgyOWQtMThiNjdiZWI3NTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA5MDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZTYxNmQzM2ZhMGY5NjY4YWYxOTgzYzU3YTJmYzFjZjhmMjdjOTM4MDI5NDg3MjJhNWJjMmQwMjkxNzU1MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KxlHuOO5mn7X8dUA42gIolZo148wurVlq3ioBQULF0o) 二维码出来是长这样，扫不了，我每次都得丢给gpt处理一遍

这是你终端字体的问题，要不换个终端，要不改个字体

**Comment by pineappleir** [comment]
> > ![image](https://private-user-images.githubusercontent.com/89891103/362601860-6cf9e36d-bd9f-4e82-829d-18b67beb7567.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjIzMDYsIm5iZiI6MTcyNDkyMjAwNiwicGF0aCI6Ii84OTg5MTEwMy8zNjI2MDE4NjAtNmNmOWUzNmQtYmQ5Zi00ZTgyLTgyOWQtMThiNjdiZWI3NTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA5MDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZTYxNmQzM2ZhMGY5NjY4YWYxOTgzYzU3YTJmYzFjZjhmMjdjOTM4MDI5NDg3MjJhNWJjMmQwMjkxNzU1MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KxlHuOO5mn7X8dUA42gIolZo148wurVlq3ioBQULF0o) 二维码出来是长这样，扫不了，我每次都得丢给gpt处理一遍
> 
> 这是你终端字体的问题，要不换个终端，要不改个字体

好的，那请问下报错是什么原因呢，我现在只有群聊里面能操作机器人，文件传输助手和设置的管理员都无法正常操作，会提示 发送消息失败，接收者为空

**Comment by Cassius0924** [comment]
发布了新版本，重新pull一下镜像，重启容器即可

**Comment by pineappleir** [comment]
> 发布了新版本，重新pull一下镜像，重启容器即可

还是不行呢
![QQ20240829-180123](https://github.com/user-attachments/assets/c5ac9ce2-960b-4d60-b546-050d1611ad54)

**Comment by Cassius0924** [comment]
> > 发布了新版本，重新pull一下镜像，重启容器即可
> 
> 
> 
> 还是不行呢
> 
> ![QQ20240829-180123](https://github.com/user-attachments/assets/c5ac9ce2-960b-4d60-b546-050d1611ad54)
> 
> 

看样子wxbotwebhook在将消息POST给wechatter的时候有问题，没发成功。看一下你的docker-cmp.yml配置

**Comment by pineappleir** [comment]
> > > 发布了新版本，重新pull一下镜像，重启容器即可
> > 
> > 
> > 还是不行呢
> > ![QQ20240829-180123](https://private-user-images.githubusercontent.com/89891103/362630479-c5ac9ce2-960b-4d60-b546-050d1611ad54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjcxNjYsIm5iZiI6MTcyNDkyNjg2NiwicGF0aCI6Ii84OTg5MTEwMy8zNjI2MzA0NzktYzVhYzljZTItOTYwYi00ZDYwLWI1NDYtMDUwZDE2MTFhZDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDEwMjEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyYzE5YzZlMDUyZDUyMjQ4NTdjNjJmMzFmZDdjYjBmNzliNGQxYjdiYzIxNWUxYjRhY2MxMTQ1ODFiODRlNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5FoF5Jd_8yU7CRD3GIVSJPrs2hEvjkI_HBTEcIgVSV4)
> 
> 看样子wxbotwebhook在将消息POST给wechatter的时候有问题，没发成功。看一下你的docker-cmp.yml配置

version: "3.8"
services:
  wxbotwebhook:
    image: dannicool/docker-wechatbot-webhook
    container_name: wxbotwebhook
    ports:
      - "3001:3001"
    environment:
      - LOGIN_API_TOKEN=wechatter
      - ACCEPT_RECVD_MSG_MYSELF=true
      - RECVD_MSG_API=http://wechatter:4000/receive_msg

  wechatter:
    image: cassius0924/wechatter
    container_name: wechatter
    ports:
      - "4000:4000"
    volumes:
      - ./config_cps.yaml:/wechatter/config.yaml
    environment:
      - WECHATTER_LOG_LEVEL=INFO
    depends_on:
      - wxbotwebhook
