### ISSUE TITLE
发送消息api解析错误

### ISSUE THREAD

**Issue by huakair** [Cassius0924/WeChatter#99]
![屏幕截图 2024-08-31 024841](https://github.com/user-attachments/assets/b9e7bd1d-fc7b-455a-bb57-474bec799dc2)
你好，微信已登录成功，从日志看也可以接收到信息，但是发送消息api显示解析失败，因是在盒子上运行的，没有固定ip，使用的是域名，尝试使用过compose的默认部署，但无法登录

**Comment by Cassius0924** [comment]
> 但是发送消息api显示解析失败，因是在盒子上运行的，没有固定ip，使用的是域名，尝试使用过compose的默认部署，但无法登录

- 什么是「盒子」？，你指的是docker吗？

- 为什么docker-compose会无法登录，提示什么？

- 如果你使用域名作为 WeChatter 接受消息的API，那你需要给你的服务器对外开放4000端口。不建议使用域名或外网IP地址，如果wechatbot-webhook和WeChatter部署在同一台机器上，建议使用内网IP地址。

**Comment by huakair** [comment]
使用了内网地址，已经成功了，可以关闭转发消息时候的引用来源吗

**Comment by Cassius0924** [comment]
> 使用了内网地址，已经成功了，可以关闭转发消息时候的引用来源吗

你指的是下面的内容吗
```
⤴️ [他] 在 [群] 说：
-------------------------
```

**Comment by huakair** [comment]
是的，能否只是单纯的转发

**Comment by Cassius0924** [comment]
> 是的，能否只是单纯的转发

目前不支持这种模式，这样会导致多个消息源无法区分。

如有需要可以尝试自行修改代码，然后用本地部署 WeChatter。
